- hosts: webserver
  vars_files:
    - vars.yml
  become: yes
  tasks:
    - name: Install latest version
      package:
        name:
          - "{{ ssl_pkg }}"
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
        state: latest

    - name: Copy conf file
      copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_dest }}"
        owner: root
        group: root
        mode: '0644'

    - name: Create directory
      file:
        path: "{{ secrets_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: '0500'

    - name: Copy auth file
      copy:
        src: "{{ secrets_src }}"
        dest: "{{ secrets_dest }}"
        owner: apache
        group: apache
        mode: '0400'

    - name: Copy htaccess file
      copy:
        src: "{{ htaccess_src }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: '0400'

    - name: Copy web content
      copy:
        content: "{{ ansible_fqdn }} ({{ ansible_default_ipv4.address }}) has been customized by Ansible."
        dest: "{{ web_root }}/index.html"
     
    - name: Start service {{ firewall_svc }}
      service:
        name: "{{ firewall_svc }}"
        state: started
        enabled: true

    - name: Allow https connection
      firewalld:
        service: https
        state: enabled
        permanent: yes
        immediate: yes

    - name: Start service {{ web_svc }}
      service:
        name: "{{ web_svc }}"
        state: started
        enabled: true


- name: Check connection
  hosts: localhost
  become: no
  vars:
    web_user: guest
  vars_files:
    - vars/secret.yml
  tasks:
    - uri:
        url: https://serverb.lab.example.com
        user: "{{ web_user }}"
        password: "{{ web_pass }}"
        validate_certs: no
        status_code: 200
        return_content: yes
      register: _result

    - debug:
        var: _result
        
