- name: Install Apache and starts the service
  hosts: webserver
  become: yes
  tasks:
    - name: Install 
      package:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['package'] }}"
        state: present

    - name: Service
      service:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['custom']['general']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['custom']['general']['enabled'] }}"
