- name: Setup repository
  hosts: all
  vars:
    custom_pkg: example-motd
  tasks:
    - name: Gather information
      package_facts:
        manager: auto

    - name: Display information
      debug:
        var: ansible_facts.packages[custom_pkg]
      when: custom_pkg in ansible_facts.packages

    - name: Configure yum repo
      yum_repository:
        name: custom_repo
        description: Example Inc. Internal YUM repo
        baseurl: http://materials.example.com/yum/repository
        gpgcheck: yes
        file: /etc/yum.repos.d/example.repo

    - name: Deploy a GPG key
      rpm_key:
        key: http://materials.example.com/yum/repository/RPM-GPG-KEY-example
        state: present

    - name: Install package
      package:
        name: '{{ custom_pkg }}'
        state: present

    - name: Gather information
      package_facts:
        manager: auto

    - name: Display information
      debug:
        var: ansible_facts.packages[custom_pkg]
      when: custom_pkg in ansible_facts.packages
