- hosts: database_prod
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
  tasks:
    - package:
        name: "{{ item }}"
        state: present
      when: ansible_os_family == "RedHat"
      loop: "{{ mariadb_packages }}"
      

    - service:
        name: mariadb
        state: started
        enabled: yes

