- hosts: devservers
  become: yes
  remote_user: devops
  vars_files:
    - secret.yml
  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
        state: present
