- name: Schedule at task
  hosts: webservers
  become: true
  become_user: devops
  tasks:
    - at:
        command: "date >> /home/devops/my_at_date_time \n"
        count: 1
        units: minutes
        unique: yes
        state: present
